homeserver: "http://synapse.railway.internal:8008"
login: "@postmoogle:your-server.up.railway.app"
password: "YourPasswordHere"
database:
  dialect: "sqlite3"
  dsn: "/data/postmoogle.db"
domains:
  - "rexform-matrix.abrdns.com"
threads: false
defaults:
  threadify: false
  nothreads: true
